### ISSUE TITLE
Please, release a new version

### ISSUE THREAD

**Issue by eribertomota** [mvertes/txt2man#11]
Hi,

The last txt2man release was 1.5.6 some years ago. Since that time, the source code had some fixes and improvements.

To make easier the packaging in several Linux distributions, as Debian, please, release a new version.

Thanks a lot in advance.

Regards,

Eriberto

**Comment by mvertes** [comment]
hello, yes will do shortly, hopefully next monday at the latest.

**Comment by eribertomota** [comment]
Thanks!

2016-08-11 11:53 GMT-03:00 Marc Vertes notifications@github.com:

**Comment by eribertomota** [comment]
New release (1.6.0) uploaded to Debian.

Thanks!

Eriberto
