### ISSUE TITLE
Requires groff dependency

### ISSUE THREAD

**Issue by ttepatti** [mvertes/txt2man#17]
Hello,

I'm currently using Debian version 9.9, kernel 4.9.0-9. On this release of Debian, the bookman utility actually requires you to apt-get install groff for it to work properly.

The command I was attempting to run:

```
sudo bookman -p -o ~/linux_man_pages.pdf *
```

Without installing this package, the program will error out with:

```
troff: fatal error: can't find macro file s
grops:<standard input>:1:fatal error: the first command must be `x T'
```

Adding the groff package as a required dependency should fix this issue.

**Comment by mvertes** [comment]
Thank you for your report and your interest in that tool. 

It is correct that txt2man depends on groff to produce ps or pdf output (but groff is not strictly required for displaying manpages only). 

I do not maintain myself the packaging for the various distributions, and this is a packaging issue here. I will just add the previous statement in the README, as an hint for package maintainers.

**Comment by eribertomota** [comment]
Hi @ttepatti,

It is a specific issue on Debian packaging for txt2man, not on txt2man directly. This issue should be reported for Debian. So, I did it here[1].

[1] https://bugs.debian.org/945045

I am the maintainer of the package in Debian and I will fix it soon.

@mvertes, I think that you can close this issue.

Cheers,

Eriberto

**Comment by eribertomota** [comment]
Hi all,

On Debian, groff install lots of other packages. So, I added groff as a suggestion[1]. The new package (1.6.0-6) is already in Debian.

[1] https://salsa.debian.org/debian/txt2man/commit/c3dbf818eea2264025dc08e8f23e375d0b03dde6

Cheers,

Eriberto

**Comment by mvertes** [comment]
Closing, as per @eribertomota request
