### ISSUE TITLE
Please, remove the check for ksh

### ISSUE THREAD

**Issue by eribertomota** [mvertes/txt2man#3]
Hi,

I am the current txt2man maintainer in Debian.

Considering that Debian creates packages for several architectures, ksh can be a problem[1]. Please, consider remove the following line from ./txt2man:

test "$HOME" = ~ || exec ksh $0 "$@"    # try ksh if sh too old (not yet POSIX)

Thanks!

Regards,

Eriberto

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=620562

**Comment by mvertes** [comment]
I agree, will remove this line. Thanks
